/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbapp;
import java.sql.*;
/**
 *
 * @author jjred88
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    static Connection con;
    static Statement st;
    static ResultSet rs;
    
    public MainGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaSearch = new javax.swing.JFrame();
        label1 = new java.awt.Label();
        txtSymptom = new java.awt.TextField();
        btnSearchGo = new java.awt.Button();
        diaLogin = new javax.swing.JFrame();
        btnClientLogin = new java.awt.Button();
        btnAdminLogin = new java.awt.Button();
        btnSearch = new java.awt.Button();

        diaSearch.setMinimumSize(new java.awt.Dimension(462, 217));

        label1.setText("Symptom: ");

        btnSearchGo.setLabel("Go");
        btnSearchGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaSearchLayout = new javax.swing.GroupLayout(diaSearch.getContentPane());
        diaSearch.getContentPane().setLayout(diaSearchLayout);
        diaSearchLayout.setHorizontalGroup(
            diaSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSearchLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diaSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaSearchLayout.createSequentialGroup()
                        .addComponent(btnSearchGo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        diaSearchLayout.setVerticalGroup(
            diaSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSearchLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(diaSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnSearchGo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout diaLoginLayout = new javax.swing.GroupLayout(diaLogin.getContentPane());
        diaLogin.getContentPane().setLayout(diaLoginLayout);
        diaLoginLayout.setHorizontalGroup(
            diaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        diaLoginLayout.setVerticalGroup(
            diaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClientLogin.setLabel("Client Login");
        btnClientLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientLoginActionPerformed(evt);
            }
        });

        btnAdminLogin.setLabel("Admin Login");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        btnSearch.setLabel("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClientLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdminLogin, btnClientLogin, btnSearch});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnClientLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientLoginActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        diaSearch.setLocationRelativeTo(null);
        diaSearch.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGoActionPerformed
        // TODO add your handling code here:
        try{
            rs = st.executeQuery("SELECT * FROM Medicine INNER JOIN Ranking ON Medicine.Generic = Ranking.Generic WHERE Ranking.Generic in (SELECT Generic from Symptoms WHERE Symptom = '" + txtSymptom.getText() + "') ORDER BY Rank DESC");
            
            /*
            SELECT field_b
FROM my_table_2 m2
WHERE EXISTS (
     SELECT my_id FROM my_table 
     WHERE field_a = 1234 and m2.my_id_2=my_table.my_id
);
            */
            
            //String med = rs.getString("Generic");
            //String sym = rs.getString("Symptom");
            System.out.println("Symptom: " + txtSymptom.getText());
            while(rs.next()){
                //String sym = rs.getString("Symptom");
                //String med = rs.getString("Generic");
                String rank = rs.getString("Rank");
                String brand = rs.getString("Brand");
                System.out.println(rank + " " + brand);//sym + " " + med);
            }
            System.out.println("*******************************************");
        }catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace(System.err);
        }
         
    }//GEN-LAST:event_btnSearchGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        String host = "jdbc:mysql://localhost:3306/DB";
        String uName="root";
        String pass = "root";
        try{
            con = DriverManager.getConnection(host, uName, pass);
            
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM Symptoms");
            /*System.out.println("********************************");
            while(rs.next()){
                String sym = rs.getString("Symptom");
                String med = rs.getString("Generic");
                System.out.println(sym + " " + med);
            }
            //System.out.println("********************************");*/
        }catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace(System.err);
        }
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAdminLogin;
    private java.awt.Button btnClientLogin;
    private java.awt.Button btnSearch;
    private java.awt.Button btnSearchGo;
    private javax.swing.JFrame diaLogin;
    private javax.swing.JFrame diaSearch;
    private java.awt.Label label1;
    private java.awt.TextField txtSymptom;
    // End of variables declaration//GEN-END:variables
}
